import random
import time


def guessNumberComputer(number):
    """
    The computer guess the number generated by user

    Args:
        number: the maximum limit marked for the number to be guessed
    """

    print("------------------------------------------" \
          "| Welcome to the guess the number game!  |"\
          "------------------------------------------"\
         f"\n\nFirst: Think of a number between 1 and {number}"\
         "\n\nYour goal is to guide the computer to guess the number that you have previously thought. \nReady!\n")
    time.sleep(5)

    # Range of valid values
    lower_bound = 1
    upper_bound = number
    response = ""

    print(f"The computer says: ")



#Setting the upper bound to guess
guessNumberComputer(100)
